added Components folder, Header & Owner loginjs files and routes
PT-Build-Week-African-Marketplace-4/front-end pull request #10
Opened 2021-07-23 04:52 UTC by Alieze-Ali

added component folder with Header & OwnerLogin files

2021-07-23 07:20 UTC, tdubs42 requested changes
Your code looks great! Your syntax is on point. I made a couple notes for some slight tweaks, but truly this is fantastic :smile:

2021-07-23 07:20 UTC, tdubs42 commented on src/App.js
> +          </Route>
Perfect route placement and awesome getting the Switch in there! :fire:

2021-07-23 07:20 UTC, tdubs42 commented on src/App.js
> +import React from 'react'; //AA
Please remove. React 17 does not require implicit React imports. We only need to import hooks such as useState, useHistory, Suspense, etc :smile:

2021-07-23 07:20 UTC, tdubs42 commented on src/App.js
> +      <Header />
To ensure no merge conflicts please remove the Header component. Jared submitted a built out NavBar just before you submitted your PR

2021-07-23 07:20 UTC, tdubs42 commented on src/components/OwnerLogin.jsx
> +import React from 'react';
Please remove the React import :smile: 

Love that you use JSX files too! For continuity in the project please switch it back to a js file as not everyone is as hip and cool as we are yet :smile:

2021-07-23 07:20 UTC, tdubs42 commented on src/components/OwnerLogin.jsx
> +// make sure to include yup
Love the note to remind you! I'm still really pushing myself to leave good notes. Love it!

2021-07-23 07:20 UTC, tdubs42 commented on src/components/OwnerLogin.jsx
> +        <div>
Unless it's purely for styling remember, div's are not your friend. For semantic HTML5 you want to either use "section" or in this case since it will be a form you can have the entire component wrapped in "form" :smile:

2021-07-24 23:26 UTC, Alieze-Ali commented on src/App.js
> +import React from 'react'; //AA
ok

2021-07-24 23:27 UTC, Alieze-Ali commented on src/App.js
> +      <Header />
Sorry, my TA insisted I add this, even though I protested - lol. May need help with this, when I try to remove - the code crashes.

2021-07-24 23:27 UTC, Alieze-Ali commented on src/components/OwnerLogin.jsx
> +import React from 'react';
Won't I need it for useState?

2021-07-24 23:30 UTC, Alieze-Ali commented on src/components/OwnerLogin.jsx
> +        <div>
ok thanks!

2021-07-24 23:37 UTC, tdubs42 requested changes
Looking good! Requested a couple changes and then this looks good to go :smile:

2021-07-24 23:37 UTC, tdubs42 commented on src/components/OwnerLogin.jsx
> +import React from 'react';
To reduce the import load you will do your import in the syntax `import { useState } from 'react';`
Only import the hooks you need instead of the entire React component :smile:

2021-07-24 23:37 UTC, tdubs42 commented on src/components/OwnerLogin.jsx
> +                </form>
After line 37 don't forget to add your submit button :smile: `<button type="submit">Login</button>`

2021-07-25 00:58 UTC, tdubs42 commented on src/App.js
> +      <Header />
We can totally check that out tonight :smile:

2021-07-26 17:33 UTC, tdubs42 commented
More recent push and merge has been made with updated components. Closing this PR to ensure we don't have merge conflicts

2021-07-26 17:33 UTC, closed without merging